#### 2. Generating password


In [10]:
import random 
import string
def password(string,value):
    pwd=string+value
    #tolist
    pwdlist=list(pwd)
    random.shuffle(pwdlist)
    empty=''
    for i in range(len(pwdlist)):
        empty+=pwdlist[i]
    print(empty)
    upper,lower,num,spe=0,0,0,0
    for i in range(len(pwd)):
        if(pwd[i]>='A' and pwd[i]<='Z'):
            upper+=1
        elif (pwd[i]>='a' and pwd[i]<='z'):
            lower+=1
        elif (pwd[i]>='0' and pwd[i]<='9'):
            num+=1
        else:
            spe+=1
var=''
special="@#$%&*^><"
for i in range(1):
    var+=random.choice(special)
for i in range(3):
    var+=random.choice(string.ascii_letters)
password(var,str(random.randint(10,99)))

8#7yIp


#### updating array by positions

In [16]:
import numpy as np
import math
def check(num):
    prime=0
    for i in  range(2,int(math.sqrt(num)+1)):
        if num%i==0:
            prime=1
            break
    if prime==0:
        return True
array=np.arange(1,26).reshape(5,5)
print(array)
print("                   ")
for i in range(len(array[0])):
    for j in range(len(array[1])):
        if check(array[i][j])==True:
            array[i][j]=array[i][j]**3
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
                   
[[    1     8    27     4   125]
 [    6   343     8     9    10]
 [ 1331    12  2197    14    15]
 [   16  4913    18  6859    20]
 [   21    22 12167    24    25]]


#### Python program to get the sum of every cubed value and its previous 
integer. 

In [67]:
def check(num):
    prime=0
    for i in  range(2,int(math.sqrt(num)+1)):
        if num%i==0:
            prime=1
            break
    if prime==0:
        return True
array7=np.arange(1,26).reshape(5,5)
listarr=array7.flatten()
for i in range(len(listarr)):
            if check(listarr[i])==True and listarr[i]!=1:
                  listarr[i]=listarr[i]**3+listarr[i-1]
# for i in range(len(listarr)):
#     print(listarr[i])
array8=np.array(listarr).reshape(5,5)
array8
                
                
     
            

array([[    1,     9,    36,     4,   129],
       [    6,   349,     8,     9,    10],
       [ 1341,    12,  2209,    14,    15],
       [   16,  4929,    18,  6877,    20],
       [   21,    22, 12189,    24,    25]])

#### 5.Array intersection

In [29]:
arr1=np.array([1, 3, 4, 5, 7])
arr2= np.array([2, 3, 5, 6])
list(filter(lambda num:num in arr1,arr2 ))

[3, 5]

#### Create a 7 x 7  2D array having only multiples of 7. And return the last 
element of the same

In [28]:
n=7*7
array2=np.arange(7,n*7+1,7).reshape(7,7)
print(array2)
print(array2)
print("Returning last element")
print(array2[-1,-1])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
Returning last element
343


#### Checker Board Patten using Numpy:
[   1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1  ]

In [67]:
array3=np.zeros((5,7))
array3
array3[0::2,0::2]=1
array3[1::2,1::2]=1
array3

array([[1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])

#### Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan

In [14]:

import numpy as np
array4=np.array([['A','B','C','D'],['E','F','G','H'],['I','a','K','L'],['M','N','o','P'],['Q','R','S','T'],['U','0','W','O' ]])
count=0
for i in range(len(array4[0])):
    for j in range(len(array4[1])):
        if array4[i][j]=='A' or array4[i][j]=='E' or array4[i][j]=='I' or array4[i][j]=='O' or array4[i][j]=='U':
                     array4[i][j]=str(np.nan)
                     count+=1

print(count)


3


In [4]:
import hashlib
import os
f1=open("D:\Random.txt",'r')
f2=open("D:\Random1.txt",'r')
f1.seek(0)
f2.seek(0)
msg1=hashlib.sha256(f1.readlines())
msg2=hashlib.sha256(f2.readlines())
up1=hashlib.sha256(msg1).hexdigest()
up2=hashlib.sha256(ms2).hexdigest()
if up1==up2:
    os.remove("D:\Random1.txt")
    print("removed")
    


TypeError: object supporting the buffer API required